-- MySQL Script generated by MySQL Workbench
-- Sat May  2 19:44:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema grtmx_bitacora_digital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema grtmx_bitacora_digital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grtmx_bitacora_digital` DEFAULT CHARACTER SET utf8 ;
USE `grtmx_bitacora_digital` ;

-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`Agencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`Agencias` (
  `idAgencia` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreAgencia` VARCHAR(355) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idAgencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`TiposAsesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`TiposAsesores` (
  `idTipoAsesor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreTipoAsesor` VARCHAR(45) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoAsesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`Asesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`Asesores` (
  `idAsesor` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(355) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellidoPaterno` VARCHAR(45) NULL DEFAULT NULL,
  `apellidoMaterno` VARCHAR(45) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  `tipoAsesor` INT(11) NOT NULL,
  `Agencias_idAgencia` INT(11) NOT NULL,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `passCrypt` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idAsesor`),
  INDEX `fk_Asesores_TiposAsesores1_idx` (`tipoAsesor` ASC),
  INDEX `fk_Asesores_Agencias1_idx` (`Agencias_idAgencia` ASC),
  CONSTRAINT `fk_Asesores_Agencias1`
    FOREIGN KEY (`Agencias_idAgencia`)
    REFERENCES `grtmx_bitacora_digital`.`Agencias` (`idAgencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asesores_TiposAsesores1`
    FOREIGN KEY (`tipoAsesor`)
    REFERENCES `grtmx_bitacora_digital`.`TiposAsesores` (`idTipoAsesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`CampaingLead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`CampaingLead` (
  `idCampaingLead` INT(11) NOT NULL,
  `nombreCampaing` VARCHAR(355) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idCampaingLead`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`VersionesVehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`VersionesVehiculos` (
  `idVersionVehiculo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreVersion` VARCHAR(355) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idVersionVehiculo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`CatalogoVehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`CatalogoVehiculos` (
  `idCatalogoVehiculo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreCatalogo` VARCHAR(300) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`idCatalogoVehiculo`),
  INDEX `fk_CatalogoVehiculos_VersionesVehiculos1_idx` (`version` ASC),
  CONSTRAINT `fk_CatalogoVehiculos_VersionesVehiculos1`
    FOREIGN KEY (`version`)
    REFERENCES `grtmx_bitacora_digital`.`VersionesVehiculos` (`idVersionVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`EtapasCitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`EtapasCitas` (
  `idEtapaCita` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreEtapa` VARCHAR(200) NULL DEFAULT NULL,
  `descripcionEtapa` MEDIUMTEXT NULL DEFAULT NULL,
  `orden` INT(11) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idEtapaCita`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`Citas` (
  `idCita` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaHoraCita` DATETIME NULL DEFAULT NULL,
  `notas` MEDIUMTEXT NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  `etapa` INT(11) NOT NULL,
  `fechaAsistida` DATETIME NULL DEFAULT NULL,
  `fechaConfirmacion` DATETIME NULL DEFAULT NULL,
  `citaConfirmada` CHAR(1) NULL DEFAULT NULL,
  `Asesor` INT(11) NOT NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_Citas_EtapasCitas1_idx` (`etapa` ASC),
  INDEX `fk_Citas_Asesores1_idx` (`Asesor` ASC),
  CONSTRAINT `fk_Citas_Asesores1`
    FOREIGN KEY (`Asesor`)
    REFERENCES `grtmx_bitacora_digital`.`Asesores` (`idAsesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citas_EtapasCitas1`
    FOREIGN KEY (`etapa`)
    REFERENCES `grtmx_bitacora_digital`.`EtapasCitas` (`idEtapaCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`EtapasLead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`EtapasLead` (
  `idEtapaLead` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreEtapa` VARCHAR(200) NULL DEFAULT NULL,
  `descripcionEtapa` MEDIUMTEXT NULL DEFAULT NULL,
  `orden` INT(11) NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idEtapaLead`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`EtapasSeguimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`EtapasSeguimientos` (
  `idEtapaSeguimiento` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreEtapaSeguimiento` VARCHAR(45) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idEtapaSeguimiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`FuentesLead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`FuentesLead` (
  `idFuenteLead` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreFuente` VARCHAR(355) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idFuenteLead`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`MetodosCompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`MetodosCompras` (
  `idMetodoCompra` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreMetodoCompra` VARCHAR(355) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idMetodoCompra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`TemperaturasLead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`TemperaturasLead` (
  `idTemperaturaLead` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreTemperatura` VARCHAR(355) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idTemperaturaLead`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`Lead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`Lead` (
  `idLead` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaRegistro` DATETIME NULL DEFAULT NULL,
  `nombreCompleto` MEDIUMTEXT NULL DEFAULT NULL,
  `nombre` VARCHAR(355) NULL DEFAULT NULL,
  `apellidoPaterno` VARCHAR(355) NULL DEFAULT NULL,
  `apellidoMaterno` VARCHAR(355) NULL DEFAULT NULL,
  `telefonoMovil` VARCHAR(10) NULL DEFAULT NULL,
  `telefonoSecundario` VARCHAR(10) NULL DEFAULT NULL,
  `correoElectronico` VARCHAR(355) NULL DEFAULT NULL,
  `fuente` INT(11) NOT NULL,
  `campaing` INT(11) NOT NULL,
  `etapa` INT(11) NOT NULL,
  `temperatura` INT(11) NOT NULL,
  `metodoCompra` INT(11) NOT NULL,
  `catalogo` INT(11) NOT NULL,
  `Agencia` INT(11) NOT NULL,
  `AsesorOnline` INT(11) NOT NULL,
  `AsesorPiso` INT(11) NOT NULL,
  `motivoPerdido` MEDIUMTEXT NULL DEFAULT NULL,
  `fechaContacto` DATETIME NULL DEFAULT NULL,
  `notas` MEDIUMTEXT NULL DEFAULT NULL,
  `fechaSiguienteActividad` DATETIME NULL DEFAULT NULL,
  `fechaSiguienteSeguimiento` DATE NULL DEFAULT NULL,
  `demoEstatica` CHAR(1) NULL DEFAULT NULL,
  `demoDinamica` CHAR(1) NULL DEFAULT NULL,
  `fechaDemoEstatica` DATETIME NULL DEFAULT NULL,
  `fechaDemoDinamica` DATETIME NULL DEFAULT NULL,
  `fechaPedido` DATETIME NULL DEFAULT NULL,
  `fechaFactura` VARCHAR(45) NULL DEFAULT NULL,
  `fechaEntrega` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idLead`),
  INDEX `fk_Lead_FuentesLead_idx` (`fuente` ASC),
  INDEX `fk_Lead_CampaingLead1_idx` (`campaing` ASC),
  INDEX `fk_Lead_TemperaturasLead1_idx` (`temperatura` ASC),
  INDEX `fk_Lead_MetodosCompras1_idx` (`metodoCompra` ASC),
  INDEX `fk_Lead_CatalogoVehiculos1_idx` (`catalogo` ASC),
  INDEX `fk_Lead_Agencias1_idx` (`Agencia` ASC),
  INDEX `fk_Lead_Asesores1_idx` (`AsesorOnline` ASC),
  INDEX `fk_Lead_Asesores2_idx` (`AsesorPiso` ASC),
  CONSTRAINT `fk_Lead_Agencias1`
    FOREIGN KEY (`Agencia`)
    REFERENCES `grtmx_bitacora_digital`.`Agencias` (`idAgencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_Asesores1`
    FOREIGN KEY (`AsesorOnline`)
    REFERENCES `grtmx_bitacora_digital`.`Asesores` (`idAsesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_Asesores2`
    FOREIGN KEY (`AsesorPiso`)
    REFERENCES `grtmx_bitacora_digital`.`Asesores` (`idAsesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_CampaingLead1`
    FOREIGN KEY (`campaing`)
    REFERENCES `grtmx_bitacora_digital`.`CampaingLead` (`idCampaingLead`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_CatalogoVehiculos1`
    FOREIGN KEY (`catalogo`)
    REFERENCES `grtmx_bitacora_digital`.`CatalogoVehiculos` (`idCatalogoVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_FuentesLead`
    FOREIGN KEY (`fuente`)
    REFERENCES `grtmx_bitacora_digital`.`FuentesLead` (`idFuenteLead`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_MetodosCompras1`
    FOREIGN KEY (`metodoCompra`)
    REFERENCES `grtmx_bitacora_digital`.`MetodosCompras` (`idMetodoCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_TemperaturasLead1`
    FOREIGN KEY (`temperatura`)
    REFERENCES `grtmx_bitacora_digital`.`TemperaturasLead` (`idTemperaturaLead`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`Etapas_Lead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`Etapas_Lead` (
  `Lead` INT(11) NOT NULL,
  `EtapasLead` INT(11) NOT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `fechaInicial` DATETIME NULL DEFAULT NULL,
  `fechaFinal` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Lead`, `EtapasLead`),
  INDEX `fk_Lead_has_EtapasLead_EtapasLead1_idx` (`EtapasLead` ASC),
  INDEX `fk_Lead_has_EtapasLead_Lead1_idx` (`Lead` ASC),
  CONSTRAINT `fk_Lead_has_EtapasLead_EtapasLead1`
    FOREIGN KEY (`EtapasLead`)
    REFERENCES `grtmx_bitacora_digital`.`EtapasLead` (`idEtapaLead`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_has_EtapasLead_Lead1`
    FOREIGN KEY (`Lead`)
    REFERENCES `grtmx_bitacora_digital`.`Lead` (`idLead`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`TiposPlantillasGuiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`TiposPlantillasGuiones` (
  `idTipoPlantillaGuion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreTiposPlantillaGuion` VARCHAR(45) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoPlantillaGuion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`PlantillasGuiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`PlantillasGuiones` (
  `idPlantillaGuion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombrePlantillaGuion` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  `TipoPlantillaGuion` INT(11) NOT NULL,
  `orden` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idPlantillaGuion`),
  INDEX `fk_PlantillasGuiones_TiposPlantillasGuiones1_idx` (`TipoPlantillaGuion` ASC),
  CONSTRAINT `fk_PlantillasGuiones_TiposPlantillasGuiones1`
    FOREIGN KEY (`TipoPlantillaGuion`)
    REFERENCES `grtmx_bitacora_digital`.`TiposPlantillasGuiones` (`idTipoPlantillaGuion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`LeadPlantillasGuiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`LeadPlantillasGuiones` (
  `Lead_idLead` INT(11) NOT NULL,
  `PlantillasGuiones_idPlantillaGuion` INT(11) NOT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Lead_idLead`, `PlantillasGuiones_idPlantillaGuion`),
  INDEX `fk_Lead_has_PlantillasGuiones_PlantillasGuiones1_idx` (`PlantillasGuiones_idPlantillaGuion` ASC),
  INDEX `fk_Lead_has_PlantillasGuiones_Lead1_idx` (`Lead_idLead` ASC),
  CONSTRAINT `fk_Lead_has_PlantillasGuiones_Lead1`
    FOREIGN KEY (`Lead_idLead`)
    REFERENCES `grtmx_bitacora_digital`.`Lead` (`idLead`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_has_PlantillasGuiones_PlantillasGuiones1`
    FOREIGN KEY (`PlantillasGuiones_idPlantillaGuion`)
    REFERENCES `grtmx_bitacora_digital`.`PlantillasGuiones` (`idPlantillaGuion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`Lead_Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`Lead_Cita` (
  `Lead` INT(11) NOT NULL,
  `Cita` INT(11) NOT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Cita`, `Lead`),
  INDEX `fk_Lead_has_Citas_Citas1_idx` (`Cita` ASC),
  INDEX `fk_Lead_has_Citas_Lead1_idx` (`Lead` ASC),
  CONSTRAINT `fk_Lead_has_Citas_Citas1`
    FOREIGN KEY (`Cita`)
    REFERENCES `grtmx_bitacora_digital`.`Citas` (`idCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_has_Citas_Lead1`
    FOREIGN KEY (`Lead`)
    REFERENCES `grtmx_bitacora_digital`.`Lead` (`idLead`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`TiposSeguimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`TiposSeguimientos` (
  `idTipoSeguimiento` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreTipoSeguimiento` VARCHAR(45) NULL DEFAULT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoSeguimiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`Seguimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`Seguimientos` (
  `idSeguimiento` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaSeguimiento` DATETIME NULL DEFAULT NULL,
  `etapa` INT(11) NOT NULL,
  `tipo` INT(11) NOT NULL,
  `Asesor` INT(11) NOT NULL,
  PRIMARY KEY (`idSeguimiento`),
  INDEX `fk_Seguimientos_EtapasSeguimientos1_idx` (`etapa` ASC),
  INDEX `fk_Seguimientos_TiposSeguimientos1_idx` (`tipo` ASC),
  INDEX `fk_Seguimientos_Asesores1_idx` (`Asesor` ASC),
  CONSTRAINT `fk_Seguimientos_Asesores1`
    FOREIGN KEY (`Asesor`)
    REFERENCES `grtmx_bitacora_digital`.`Asesores` (`idAsesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seguimientos_EtapasSeguimientos1`
    FOREIGN KEY (`etapa`)
    REFERENCES `grtmx_bitacora_digital`.`EtapasSeguimientos` (`idEtapaSeguimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seguimientos_TiposSeguimientos1`
    FOREIGN KEY (`tipo`)
    REFERENCES `grtmx_bitacora_digital`.`TiposSeguimientos` (`idTipoSeguimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grtmx_bitacora_digital`.`Lead_Seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grtmx_bitacora_digital`.`Lead_Seguimiento` (
  `Lead` INT(11) NOT NULL,
  `Seguimiento` INT(11) NOT NULL,
  `fechaSeguimiento` DATETIME NULL DEFAULT NULL,
  `activo` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`Lead`, `Seguimiento`),
  INDEX `fk_Lead_has_Seguimientos_Seguimientos1_idx` (`Seguimiento` ASC),
  INDEX `fk_Lead_has_Seguimientos_Lead1_idx` (`Lead` ASC),
  CONSTRAINT `fk_Lead_has_Seguimientos_Lead1`
    FOREIGN KEY (`Lead`)
    REFERENCES `grtmx_bitacora_digital`.`Lead` (`idLead`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lead_has_Seguimientos_Seguimientos1`
    FOREIGN KEY (`Seguimiento`)
    REFERENCES `grtmx_bitacora_digital`.`Seguimientos` (`idSeguimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
